package com.naveen.ndr.engine;

import com.naveen.ndr.model.DisasterEvent;

import java.util.Comparator;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.concurrent.PriorityBlockingQueue;

/**
 * EventQueueManager
 * Centralized manager for creating and exposing the two core queues used in the
 * simulation:
 *   1) producerQueue  – Raw events generated by StateNode threads
 *   2) dispatchQueue  – Priority queue sorted by severity for the Dispatcher
 * This class isolates queue creation, configuration, and access in one place so
 * that Coordinator, Dispatcher, and StateNodes do not worry about queue setup.
 */
public class EventQueueManager {

    /**
     * Queue for raw events from StateNode producers.
     * Unbounded LinkedBlockingQueue to ensure producers never block due to size.
     */
    private final BlockingQueue<DisasterEvent> producerQueue;

    /**
     * Priority queue for ranked severity events.
     * Highest severity first using Comparator.
     */
    private final PriorityBlockingQueue<DisasterEvent> dispatchQueue;

    public EventQueueManager() {
        this.producerQueue = new LinkedBlockingQueue<>();

        // Comparator: higher severity → higher priority
        Comparator<DisasterEvent> comparator = (a, b) -> Integer.compare(b.getSeverityScore(), a.getSeverityScore());

        this.dispatchQueue = new PriorityBlockingQueue<>(100, comparator);
    }

    public BlockingQueue<DisasterEvent> getProducerQueue() {
        return producerQueue;
    }

    public PriorityBlockingQueue<DisasterEvent> getDispatchQueue() {
        return dispatchQueue;
    }

    /**
     * Optional: clear both queues (useful for reset or testing)
     */
    public void clear() {
        producerQueue.clear();
        dispatchQueue.clear();
    }

    @Override
    public String toString() {
        return "EventQueueManager{" +
                "producerQueueSize=" + producerQueue.size() +
                ", dispatchQueueSize=" + dispatchQueue.size() +
                '}';
    }
}
